apiVersion: batch/v1
kind: Job
metadata:
  name: kubediag-admission-create
  namespace: kubediag
spec:
  template:
    metadata:
      name: kubediag-admission-create
    spec:
      containers:
      - name: create
        image: jettech/kube-webhook-certgen:v1.5.2
        imagePullPolicy: IfNotPresent
        args:
        - create
        - --cert-name=tls.crt
        - --key-name=tls.key
        - --host=,$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
        - --namespace=kubediag
        - --secret-name=webhook-server-cert
        resources: {}
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      serviceAccountName: kubediag 
