
apiVersion: v1
kind: Service
metadata:
  name: kubediag-webhook-service
  namespace: kubediag
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: kubediag
    mode: master
